# Generated by Django 3.2.8 on 2021-12-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fav_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.movie_list')),
            ],
        ),
    ]
